version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    network_mode: "bridge"

  # server:
  #   image: ghcr.io/guillaumedorschner/serserver-flask:latest
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - db