version: '3'
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "80:80"
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - server
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    network_mode: "bridge"