name: Release Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release Package
        run: |
          mkdir release
          cp example.env release/
          cp init.sql release/
          cp docker-compose.yml release/
          cd release
          zip -r release_package.zip .

      - name: Upload Release Package
        uses: actions/upload-artifact@v2
        with:
          name: release-package
          path: release/release_package.zip
